In [48]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

import FourierGalerkin_Burgers
# Reloading the module
import importlib
importlib.reload(FourierGalerkin_Burgers)
from FourierGalerkin_Burgers import *

In [53]:
# Testing Direct convolutionalsum
N = 4
V = np.arange(1, 5+1)
W = np.ones(5)
print("V: ", V)
print("W: ", W)
print('Conv Sum of VW\n', CalConvSum_Direct(V,W))
print('Conv Sum of WV\n', CalConvSum_Direct(W,V))
print('Conv Sum of VW by DFT\n', CalConvSum_DFT(V,W))
print('Conv Sum of WV by DFT\n', CalConvSum_DFT(W,V))

V:  [1 2 3 4 5]
W:  [1. 1. 1. 1. 1.]
Conv Sum of VW
 [ 6. 10. 15. 14. 12.]
Conv Sum of WV
 [ 6. 10. 15. 14. 12.]
Conv Sum of VW by DFT
 [ 6.+0.j 10.+0.j 15.+0.j 14.+0.j 12.+0.j]
Conv Sum of WV by DFT
 [ 6.+0.j 10.+0.j 15.+0.j 14.+0.j 12.+0.j]


In [54]:
N = 4
V = np.random.rand(5)
W = np.random.rand(5)
print('Conv Sum of VW\n', CalConvSum_Direct(V,W))
print('Conv Sum of WV\n', CalConvSum_Direct(W,V))
print('Conv Sum of VW by DFT\n', CalConvSum_DFT(V,W))
print('Conv Sum of WV by DFT\n', CalConvSum_DFT(W,V))

Conv Sum of VW
 [0.57372223 1.0806801  1.4935707  1.68482379 1.31282583]
Conv Sum of WV
 [0.57372223 1.0806801  1.4935707  1.68482379 1.31282583]
Conv Sum of VW by DFT
 [0.57372223+0.j 1.0806801 +0.j 1.4935707 +0.j 1.68482379+0.j
 1.31282583+0.j]
Conv Sum of WV by DFT
 [0.57372223+0.j 1.0806801 +0.j 1.4935707 +0.j 1.68482379+0.j
 1.31282583+0.j]
