In [16]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from scipy import linalg
from numpy.linalg import inv


# Reloading the module
import importlib

import OrthogonalPolynomials
importlib.reload(OrthogonalPolynomials)
from OrthogonalPolynomials import *

import GeneralFunctionality
importlib.reload(GeneralFunctionality)
from GeneralFunctionality import *

In [17]:
# Testing the tridiagonal solver
def CreateTridiagonal():
    N = 4
    d = np.array([6,7,8,9,10], dtype=np.double)
    l = np.array([0,1,2,1,2], dtype=np.double)
    u = np.array([3,1,1,3,0], dtype=np.double)
    y = np.array([1,2,3,4,5], dtype=np.double)
    A = np.zeros((N+1, N+1), dtype=np.double)
    
    for i in range(N+1):
        A[i,i] = d[i]
    for i in range(1,N+1):
        A[i,i-1] = l[i]
    for i in range(N):
        A[i,i+1] = u[i]
        
    
    return N, d, l, u, y, A



N, d, l, u, y, A = CreateTridiagonal()
x = TridiagonalSolver(N, d, l, u, y)
print("Solution mine\n", x)

# scipy
N, d, l, u, y, A = CreateTridiagonal()
x = linalg.solve(A, y)
print("Solution linalg.solve\n", x)

# numpy inverse matrix
x = np.dot(inv(A),y)
print("Solution numpy.linalg.inv\n", x)


Solution mine
 [0.04735994 0.23861346 0.28234583 0.26400645 0.44719871]
Solution linalg.solve
 [0.04735994 0.23861346 0.28234583 0.26400645 0.44719871]
Solution numpy.linalg.inv
 [0.04735994 0.23861346 0.28234583 0.26400645 0.44719871]


In [19]:
x = np.array([4,13,1,4,3])
print("np.dot(A, x)", np.dot(A, x))
print("TridiagonalMultiplication", TridiagonalMultiplication(d,l,u,x))

np.dot(A, x) [63. 96. 38. 46. 38.]
TridiagonalMultiplication [63. 96. 38. 46. 38.]
