In [18]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Reloading the module
import importlib

import OrthogonalPolynomials
importlib.reload(OrthogonalPolynomials)
from OrthogonalPolynomials import *

import GeneralFunctionality
importlib.reload(GeneralFunctionality)
from GeneralFunctionality import *

import Potential2D
importlib.reload(Potential2D)
from Potential2D import *

from scipy.special import eval_legendre, roots_legendre
from scipy import integrate

In [2]:
# Testing the index maps
N = 4
M = 2
A = np.empty((N,M), dtype=object)
for i in range(N):
    for j in range(M):
        A[i,j] = str(i)+str(j)
        
print(A)

A_1D = np.empty((N*M), dtype=object)
for i in range(N):
    for j in range(M):
        n = index_2D_to_1D(i,j,M)
        A_1D[n] = A[i,j]
        
print(A_1D)

B = np.empty((N,M), dtype=object)
for n in range(N*M):
    i,j = index_1D_to_2D(n,M)
    B[i,j] = A_1D[n]
    
print(B)        

[['00' '01']
 ['10' '11']
 ['20' '21']
 ['30' '31']]
['00' '01' '10' '11' '20' '21' '30' '31']
[['00' '01']
 ['10' '11']
 ['20' '21']
 ['30' '31']]


In [3]:
# Testing the matrix equation solver
N = 3
M = 3
A = np.arange(N*N).reshape(N,N)
B = np.arange(M*M).reshape(M,M)
#B = np.zeros(M*M).reshape(M,M)
U0 = np.ones((N,M))
S = np.dot(A, U0) + np.dot(U0, B)
U = MatEqnSolver(A, B, S, N, M)
print("Solution:\n", U)
print("S:\n", S)
print("RHS:\n", np.dot(A, U) + np.dot(U, B))
print("RHS U0:\n", np.dot(A, U) + np.dot(U, B))

Solution:
 [[ 5. -7.  5.]
 [-7. 17. -7.]
 [ 5. -7.  5.]]
S:
 [[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]
RHS:
 [[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]
RHS U0:
 [[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]


In [4]:
# Testing the matrix equation solver
N = 4
M = 7
A = np.random.rand(N,N)
B = np.random.rand(M,M)
U0 = np.ones((N,M))
S = np.dot(A, U0) + np.dot(U0, B)
U = MatEqnSolver(A, B, S, N, M)
print("Solution:\n", U)
print("S:\n", S)
print("RHS:\n", np.dot(A, U) + np.dot(U, B))
print("RHS U0:\n", np.dot(A, U) + np.dot(U, B))

Solution:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
S:
 [[6.84330092 6.75954352 6.83498915 6.16705602 6.67264661 5.9330296
  6.80868144]
 [6.43897574 6.35521834 6.43066397 5.76273084 6.26832143 5.52870442
  6.40435626]
 [6.899012   6.8152546  6.89070023 6.2227671  6.72835769 5.98874068
  6.86439252]
 [6.18980541 6.10604801 6.18149364 5.51356051 6.0191511  5.27953409
  6.15518593]]
RHS:
 [[6.84330092 6.75954352 6.83498915 6.16705602 6.67264661 5.9330296
  6.80868144]
 [6.43897574 6.35521834 6.43066397 5.76273084 6.26832143 5.52870442
  6.40435626]
 [6.899012   6.8152546  6.89070023 6.2227671  6.72835769 5.98874068
  6.86439252]
 [6.18980541 6.10604801 6.18149364 5.51356051 6.0191511  5.27953409
  6.15518593]]
RHS U0:
 [[6.84330092 6.75954352 6.83498915 6.16705602 6.67264661 5.9330296
  6.80868144]
 [6.43897574 6.35521834 6.43066397 5.76273084 6.26832143 5.52870442
  6.40435626]
 [6.899012   6.8152546  6.89070023 6.2227671  6.728357

In [8]:
# Testing the Kronecker product
A = np.arange(1,6+1).reshape(2,3)
B = np.identity(2)
print("A\n", A)
print("B\n", B)
print(r"$A \otimes B$", '\n', np.kron(A, B))

A
 [[1 2 3]
 [4 5 6]]
B
 [[1. 0.]
 [0. 1.]]
$A \otimes B$ 
 [[1. 0. 2. 0. 3. 0.]
 [0. 1. 0. 2. 0. 3.]
 [4. 0. 5. 0. 6. 0.]
 [0. 4. 0. 5. 0. 6.]]


In [14]:
# Testing reshape
A.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [21]:
# Testing the matrix equation solver
N = 4
M = 7
A = np.random.rand(N,N)
B = np.random.rand(M,M)
U0 = np.ones((N,M))
S = np.dot(A, U0) + np.dot(U0, B)
U = MatEqnSolver(A, B, S, N, M, Converter=MatEqnConverter2)
print("Solution:\n", U)
print("S:\n", S)
print("RHS:\n", np.dot(A, U) + np.dot(U, B))
print("RHS U0:\n", np.dot(A, U) + np.dot(U, B))

Solution:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
S:
 [[5.85087459 6.31372782 6.66694872 5.81986123 7.69444601 6.18774397
  7.3961014 ]
 [4.86786294 5.33071617 5.68393707 4.83684957 6.71143436 5.20473232
  6.41308975]
 [3.94137547 4.4042287  4.7574496  3.9103621  5.78494689 4.27824485
  5.48660228]
 [5.23197476 5.69482799 6.04804889 5.20096139 7.07554618 5.56884414
  6.77720157]]
RHS:
 [[5.85087459 6.31372782 6.66694872 5.81986123 7.69444601 6.18774397
  7.3961014 ]
 [4.86786294 5.33071617 5.68393707 4.83684957 6.71143436 5.20473232
  6.41308975]
 [3.94137547 4.4042287  4.7574496  3.9103621  5.78494689 4.27824485
  5.48660228]
 [5.23197476 5.69482799 6.04804889 5.20096139 7.07554618 5.56884414
  6.77720157]]
RHS U0:
 [[5.85087459 6.31372782 6.66694872 5.81986123 7.69444601 6.18774397
  7.3961014 ]
 [4.86786294 5.33071617 5.68393707 4.83684957 6.71143436 5.20473232
  6.41308975]
 [3.94137547 4.4042287  4.7574496  3.9103621  5.784