In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Reloading the module
import importlib

import OrthogonalPolynomials
importlib.reload(OrthogonalPolynomials)
from OrthogonalPolynomials import *

import GeneralFunctionality
importlib.reload(GeneralFunctionality)
from GeneralFunctionality import *

import Potential2D
importlib.reload(Potential2D)
from Potential2D import *

from scipy.special import eval_legendre, roots_legendre
from scipy import integrate

In [2]:
# Testing the index maps
N = 4
M = 2
A = np.empty((N,M), dtype=object)
for i in range(N):
    for j in range(M):
        A[i,j] = str(i)+str(j)
        
print(A)

A_1D = np.empty((N*M), dtype=object)
for i in range(N):
    for j in range(M):
        n = index_2D_to_1D(i,j,M)
        A_1D[n] = A[i,j]
        
print(A_1D)

B = np.empty((N,M), dtype=object)
for n in range(N*M):
    i,j = index_1D_to_2D(n,M)
    B[i,j] = A_1D[n]
    
print(B)        

[['00' '01']
 ['10' '11']
 ['20' '21']
 ['30' '31']]
['00' '01' '10' '11' '20' '21' '30' '31']
[['00' '01']
 ['10' '11']
 ['20' '21']
 ['30' '31']]


In [3]:
# Testing the matrix equation solver
N = 3
M = 3
A = np.arange(N*N).reshape(N,N)
B = np.arange(M*M).reshape(M,M)
#B = np.zeros(M*M).reshape(M,M)
U0 = np.ones((N,M))
S = np.dot(A, U0) + np.dot(U0, B)
U = MatEqnSolver(A, B, S, N, M)
print("Solution:\n", U)
print("S:\n", S)
print("RHS:\n", np.dot(A, U) + np.dot(U, B))
print("RHS U0:\n", np.dot(A, U) + np.dot(U, B))

Solution:
 [[ 5. -7.  5.]
 [-7. 17. -7.]
 [ 5. -7.  5.]]
S:
 [[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]
RHS:
 [[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]
RHS U0:
 [[12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]


In [4]:
# Testing the matrix equation solver
N = 4
M = 7
A = np.random.rand(N,N)
B = np.random.rand(M,M)
U0 = np.ones((N,M))
S = np.dot(A, U0) + np.dot(U0, B)
U = MatEqnSolver(A, B, S, N, M)
print("Solution:\n", U)
print("S:\n", S)
print("RHS:\n", np.dot(A, U) + np.dot(U, B))
print("RHS U0:\n", np.dot(A, U) + np.dot(U, B))

Solution:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
S:
 [[5.45771974 5.37253723 6.14951733 5.32863458 4.93323882 4.66990582
  5.5604789 ]
 [4.91708263 4.83190012 5.60888021 4.78799747 4.39260171 4.12926871
  5.01984179]
 [5.71671652 5.63153401 6.40851411 5.58763136 5.1922356  4.92890261
  5.81947569]
 [6.37535375 6.29017124 7.06715134 6.2462686  5.85087283 5.58753984
  6.47811292]]
RHS:
 [[5.45771974 5.37253723 6.14951733 5.32863458 4.93323882 4.66990582
  5.5604789 ]
 [4.91708263 4.83190012 5.60888021 4.78799747 4.39260171 4.12926871
  5.01984179]
 [5.71671652 5.63153401 6.40851411 5.58763136 5.1922356  4.92890261
  5.81947569]
 [6.37535375 6.29017124 7.06715134 6.2462686  5.85087283 5.58753984
  6.47811292]]
RHS U0:
 [[5.45771974 5.37253723 6.14951733 5.32863458 4.93323882 4.66990582
  5.5604789 ]
 [4.91708263 4.83190012 5.60888021 4.78799747 4.39260171 4.12926871
  5.01984179]
 [5.71671652 5.63153401 6.40851411 5.58763136 5.192

In [5]:
# Testing the Kronecker product
A = np.arange(1,6+1).reshape(2,3)
B = np.identity(2)
print("A\n", A)
print("B\n", B)
print(r"$A \otimes B$", '\n', np.kron(A, B))

A
 [[1 2 3]
 [4 5 6]]
B
 [[1. 0.]
 [0. 1.]]
$A \otimes B$ 
 [[1. 0. 2. 0. 3. 0.]
 [0. 1. 0. 2. 0. 3.]
 [4. 0. 5. 0. 6. 0.]
 [0. 4. 0. 5. 0. 6.]]


In [6]:
# Testing reshape
A.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [7]:
# Testing the matrix equation solver
N = 4
M = 7
A = np.random.rand(N,N)
B = np.random.rand(M,M)
U0 = np.ones((N,M))
S = np.dot(A, U0) + np.dot(U0, B)
U = MatEqnSolver(A, B, S, N, M, Converter=MatEqnConverter2)
print("Solution:\n", U)
print("S:\n", S)
print("RHS:\n", np.dot(A, U) + np.dot(U, B))
print("RHS U0:\n", np.dot(A, U) + np.dot(U, B))

Solution:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
S:
 [[4.64508153 5.2015223  5.75256153 6.05378568 5.44407085 6.35098232
  5.39247433]
 [4.67513611 5.23157688 5.78261611 6.08384026 5.47412543 6.3810369
  5.42252891]
 [5.24110017 5.79754094 6.34858017 6.64980433 6.0400895  6.94700097
  5.98849297]
 [5.11419321 5.67063398 6.22167321 6.52289737 5.91318253 6.820094
  5.86158601]]
RHS:
 [[4.64508153 5.2015223  5.75256153 6.05378568 5.44407085 6.35098232
  5.39247433]
 [4.67513611 5.23157688 5.78261611 6.08384026 5.47412543 6.3810369
  5.42252891]
 [5.24110017 5.79754094 6.34858017 6.64980433 6.0400895  6.94700097
  5.98849297]
 [5.11419321 5.67063398 6.22167321 6.52289737 5.91318253 6.820094
  5.86158601]]
RHS U0:
 [[4.64508153 5.2015223  5.75256153 6.05378568 5.44407085 6.35098232
  5.39247433]
 [4.67513611 5.23157688 5.78261611 6.08384026 5.47412543 6.3810369
  5.42252891]
 [5.24110017 5.79754094 6.34858017 6.64980433 6.0400895  6

In [89]:
# Testing the Nodal Galerkin solver
N = 10
M = 8
U = np.random.rand(N,M)
E = np.random.rand(N,M) * 1
F = np.random.rand(N,M) * 2
A = np.random.rand(N,N) * 3
B = np.random.rand(M,M) * 4
S = np.matmul(A, U) * E + np.matmul(U, B) * F
U_sol = MatEqnSolver_NodalGalerkin(A, B, S, E, F, N, M)
print("Error\n", np.max(U - U_sol))

Error
 6.750155989720952e-14
