In [248]:
import numpy as np

# Reloading the module
import importlib

import IterSolv
importlib.reload(IterSolv)


from scipy.sparse import csc_matrix
from scipy.sparse.linalg import cg
from scipy.sparse.linalg import bicgstab

In [2]:
# Testing the Jacobi solver
# Example 8.1 in Qingyang Li's book
A = np.array([[8,-3,2],[4,11,-1], [6,3,12]])
b = np.array([20,33,36])
x, err = IterSolv.Jacobi(A, b, maxiter=30, tol=1e-8)
print("Solution:\n", x)
print("Maximum absolute error:\n", err)

Solution:
 [3. 2. 1.]
Maximum absolute error:
 2.442821611658985e-09


In [3]:
# Testing the Gauss Seidel solver
# Example 8.1 in Qingyang Li's book
A = np.array([[8,-3,2],[4,11,-1], [6,3,12]])
b = np.array([20,33,36])
x, err = IterSolv.GaussSeidel(A, b, maxiter=20, tol=1e-8)
print("Solution:\n", x)
print("Maximum absolute error:\n", err)

Solution:
 [3. 2. 1.]
Maximum absolute error:
 6.403133134824657e-09


In [4]:
# Comparison between Jacobi and Gauss-Seidel
# An example where Jacobi works but Gaus-Seidel doesn't.
A = np.array([[1,0,1],[-1,1,0], [1,2,-3]])
b = np.array([1,1,1])
x_J, err_J = IterSolv.Jacobi(A, b, maxiter=10000, tol=1e-8)
x_GS, err_GS = IterSolv.GaussSeidel(A, b, maxiter=10000, tol=1e-8)
print("Jacobi:")
print("Solution:\n", x_J)
print("Maximum absolute error:\n", err_J)
print("Gauss-Seidel:")
print("Solution:\n", x_GS)
print("Maximum absolute error:\n", err_GS)

Jacobi:
Solution:
 [0.33333333 1.33333334 0.66666667]
Maximum absolute error:
 8.797295780738068e-09
Gauss-Seidel:
Solution:
 [-0.33333333  0.66666667 -0.        ]
Maximum absolute error:
 1.333333333333333


In [5]:
# Comparison between Jacobi and Gauss-Seidel
# An example where Gaus-Seidel works but Jacobi doesn't.
A = np.array([[1, 0.5, 0.5], [0.5, 1, 0.5], [0.5, 0.5, 1]])
b = np.array([1,1,1])
x_J, err_J = IterSolv.Jacobi(A, b, maxiter=20, tol=1e-8)
x_GS, err_GS = IterSolv.GaussSeidel(A, b, maxiter=20, tol=1e-8)
print("Jacobi:")
print("Solution:\n", x_J)
print("Maximum absolute error:\n", err_J)
print("Gauss-Seidel:")
print("Solution:\n", x_GS)
print("Maximum absolute error:\n", err_GS)

Jacobi:
Solution:
 [0. 0. 0.]
Maximum absolute error:
 1.0
Gauss-Seidel:
Solution:
 [0.5 0.5 0.5]
Maximum absolute error:
 5.537250657994264e-09


In [6]:
# Comparison between SOR and Gauss-Seidel
# An example where Jacobi works but Gaus-Seidel doesn't.
# In this case, underrelaxation works, but overrelaxation doesn't
A = np.array([[1,0,1],[-1,1,0], [1,2,-3]])
b = np.array([1,1,1])
x_SOR, err_SOR = IterSolv.SOR(A, b, w=0.85, maxiter=100, tol=1e-8)
x_GS, err_GS = IterSolv.GaussSeidel(A, b, maxiter=100, tol=1e-8)
print("SOR:")
print("Solution:\n", x_SOR)
print("Maximum absolute error:\n", err_SOR)
print("Gauss-Seidel:")
print("Solution:\n", x_GS)
print("Maximum absolute error:\n", err_GS)

SOR:
Solution:
 [0.33333333 1.33333333 0.66666667]
Maximum absolute error:
 1.9473840318084967e-09
Gauss-Seidel:
Solution:
 [-0.33333333  0.66666667 -0.        ]
Maximum absolute error:
 1.333333333333333


In [7]:
# Testing the conjugate gradient method
N = 10
A = np.random.rand(N, N)
A = np.dot(A, A.T)
#A = A + A.T
b = np.random.rand(N)

x, err = IterSolv.CG(A, b, maxiter=N, tol=1e-8)
print("Solution:\n", x)

x_np = np.linalg.solve(A, b)
print("Numpy Solution:\n", x_np)


print("CG Maximum absolute error:\n", err)
print("np Maximum absolute error:\n", np.linalg.norm(b - np.dot(A,x_np), ord=np.inf))


Solution:
 [-7.52435208 -0.97368909 -5.62367059 -1.30665435  0.31592265  5.80355835
  1.80776131 -0.80671437 -1.53978023 10.40517458]
Numpy Solution:
 [-52.46812754  -9.57118795 -13.28824604 -45.89299872  14.61070991
  37.2306435   36.36879161 -39.40474245   1.89764648  74.8107165 ]
CG Maximum absolute error:
 0.695888800445899
np Maximum absolute error:
 5.895284260759581e-14


In [8]:
# Testing the Jacobi preconditioned conjugate gradient method
N = 100
A = np.random.rand(N, N)
#A = np.dot(A, A.T)
A = A + A.T
b = np.random.rand(N)
x, err = IterSolv.CG_JacobiPrecond(A, b, maxiter=2*N, tol=1e-8)
print("Solution:\n", x[0:6])

x_np = np.linalg.solve(A, b)
print("Numpy Solution:\n", x_np[0:6])


#print("CG Maximum absolute error:\n", err)
#print("np Maximum absolute error:\n", np.linalg.norm(b - np.dot(A,x_np), ord=np.inf))


Solution:
 [ 0.19508744 -1.57233932 -0.31186801  0.51115242 -0.40705112 -0.26788039]
Numpy Solution:
 [-0.19175092 -1.19623939 -0.70165554  0.56660481 -0.33003274 -0.11953811]


In [9]:
# Scipy conjugate gradient method
N = 1000
A = np.random.rand(N, N)
#A = np.dot(A, A.T)
A = A + A.T
A_sparse = csc_matrix(A)
b = np.random.rand(N)

x, exit_code = cg(A, b, atol=1e-5)
print("Success if 0:", exit_code)
print("Solution:\n", x[0:6])

#x_np = np.linalg.solve(A, b)
#print("Numpy Solution:\n", x_np[0:6])

Success if 0: 0
Solution:
 [-0.34601188 -0.00641165  1.51442551  1.17245205 -0.75297386  0.62503911]


In [309]:
# Testing the BICGSTAB
N = 30
A = np.random.rand(N, N)
A_sparse = csc_matrix(A)
b = np.random.rand(N)
x, exit_code = bicgstab(A_sparse, b, atol=1e-8)
print("Solution:\n", x[0:5])
print("exit code:", exit_code)

x_np = np.linalg.solve(A, b)
print("Numpy Solution:\n", x_np[0:5])

Solution:
 [ 1.60019128  0.20875494  0.38059144  0.67497013 -0.26124581]
exit code: -10
Numpy Solution:
 [-0.25138877  0.84288645 -0.15721588  0.30648485  0.61765559]
